# -*- coding: utf-8 -*-
"""Builds the AI Open (Elsevier/KeAi) LaTeX submission from content_blocks.py,
the same structured content used for the AIA docx build. Author-year (natbib)
citations via cas-refs.bib / refkey_to_bibkey.json, generated by
build_bib.py (see manuscript/latex/cas-refs.bib).
"""
import json
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
LATEX_DIR = os.path.join(HERE, "latex")
FIGDIR = os.path.join(HERE, "figures")
sys.path.insert(0, HERE)
import content_blocks as C

REFKEY_TO_BIBKEY = json.load(open(os.path.join(LATEX_DIR, "refkey_to_bibkey.json"), encoding="utf-8"))
CITE_RE = re.compile(r"‹([\d,]+)›")

# ---------------------------------------------------------------------------
# Text escaping for plain prose -> LaTeX
# ---------------------------------------------------------------------------
_ESCAPE_MAP = {
    "&": r"\&", "%": r"\%", "#": r"\#", "$": r"\$",
    "{": r"\{", "}": r"\}",
    "_": r"\_\allowbreak{}",
    "“": "``", "”": "''", "‘": "`", "’": "'",
    "—": "---", "–": "--",
    "×": r"$\times$", "→": r"$\rightarrow$", "≈": r"$\approx$",
    "≥": r"$\geq$", "≤": r"$\leq$", "±": r"$\pm$",
    "…": r"\ldots{}",
    "′": "'",
    "←": r"$\leftarrow$",
    "−": r"$-$",
    "∞": r"$\infty$",
    "Σ": r"$\Sigma$",
    "▷": r"$\triangleright$",
}

_COMBINING_HAT_RE = re.compile(r"(.)̂")


URL_RE = re.compile(r"https?://\S+")


def esc(text):
    # Protect citation tokens and raw URLs (wrapped in \url{}, not hand-escaped)
    protected = []
    i = 0
    for m in CITE_RE.finditer(text):
        protected.append((m.start(), m.end(), m.group(0)))
    for m in URL_RE.finditer(text):
        url = m.group(0).rstrip(".,;)")
        protected.append((m.start(), m.start() + len(url), r"\url{" + url + "}"))
    protected.sort()
    out = []
    i = 0
    for start, end, replacement in protected:
        out.append(_escape_plain(text[i:start]))
        out.append(replacement)
        i = end
    out.append(_escape_plain(text[i:]))
    return "".join(out)


def _escape_plain(s):
    for k, v in _ESCAPE_MAP.items():
        s = s.replace(k, v)
    s = _COMBINING_HAT_RE.sub(lambda m: f"$\\hat{{{m.group(1)}}}$", s)
    return s


_MANUAL_NUM_RE = re.compile(r"^(Figure|Table|Algorithm)\s+\d+\.\s*")
_APPENDIX_NUM_RE = re.compile(r"^Appendix\s+[A-Z]\.\s*")


def strip_manual_number(text):
    """content_blocks.py captions are hand-numbered for the DOCX build (no
    auto-numbering there); LaTeX's \\caption numbers automatically, so drop
    the leading "Figure N."/"Table N."/"Algorithm N." to avoid double numbering."""
    return _MANUAL_NUM_RE.sub("", text, count=1)


def strip_appendix_label(text):
    """Same idea as strip_manual_number, for H1 appendix headings: after \\appendix is
    issued, LaTeX auto-prefixes "Appendix A/B/C..." to each \\section, so drop the
    hand-written "Appendix X. " prefix used for the DOCX build to avoid double-labeling."""
    return _APPENDIX_NUM_RE.sub("", text, count=1)


def resolve_citations(text):
    def _sub(m):
        keys = [REFKEY_TO_BIBKEY[f"reference_{n.strip()}"] for n in m.group(1).split(",")]
        return r"\citep{" + ",".join(keys) + "}"
    return CITE_RE.sub(_sub, esc(text))


# ---------------------------------------------------------------------------
def latex_body():
    out = []
    for b in C.BLOCKS:
        t = b["type"]
        if t == "appendix_start":
            out.append(r"\appendix")
        elif t == "h1":
            out.append(f"\\section{{{esc(strip_appendix_label(b['text']))}}}")
        elif t == "h2":
            out.append(f"\\subsection{{{esc(b['text'])}}}")
        elif t == "h3":
            out.append(f"\\subsubsection{{{esc(b['text'])}}}")
        elif t == "p":
            out.append(resolve_citations(b["text"]))
        elif t == "bullets":
            out.append(r"\begin{itemize}")
            for head, body in b["items"]:
                out.append(f"\\item \\textbf{{{esc(head)}}} {resolve_citations(body)}")
            out.append(r"\end{itemize}")
        elif t == "figure":
            path = os.path.join(FIGDIR, b["path"])
            width = r"\linewidth" if b["full"] else r"0.85\linewidth"
            out.append(r"\begin{figure}[htbp]")
            out.append(r"\centering")
            out.append(f"\\includegraphics[width={width}]{{{path}}}")
            out.append(f"\\caption{{{resolve_citations(strip_manual_number(b['caption']))}}}")
            out.append(r"\end{figure}")
        elif t == "code":
            out.append(r"\begin{figure}[htbp]")
            out.append(r"\centering")
            out.append(r"\begin{quote}\ttfamily\small")
            for ln in b["lines"]:
                safe = _escape_plain(ln) if ln.strip() else "~"
                out.append(safe + r"\\{}")
            out.append(r"\end{quote}")
            if b.get("caption"):
                out.append(f"\\caption{{{resolve_citations(strip_manual_number(b['caption']))}}}")
            out.append(r"\end{figure}")
        elif t == "algo":
            out.append(latex_algo(b))
        elif t == "table":
            out.append(latex_table(b))
        else:
            raise ValueError(t)
        out.append("")
    return "\n".join(out)


def latex_algo(b):
    lines = [r"\begin{algorithm}[htbp]", f"\\caption{{{esc(strip_manual_number(b['title']))}}}", r"\begin{algorithmic}[1]"]
    lines.append(r"\Require " + resolve_citations(b["require"]))
    lines.append(r"\Ensure " + resolve_citations(b["ensure"]))
    for raw in b["steps"]:
        s = raw.strip()
        # strip a trailing "▷ comment" into a \Comment{}
        comment = ""
        cm = re.search(r"\s*▷\s*(.*)$", s)
        if cm:
            comment = f" \\Comment{{{_escape_plain(cm.group(1).strip())}}}"
            s = s[:cm.start()]
        low = s.lower()
        if re.match(r"^for\s.*\sdo$", low):
            body = re.sub(r"\s*do$", "", s, flags=re.I)
            body = re.sub(r"^for\s+", "", body, flags=re.I)
            lines.append(f"\\For{{{_escape_plain(body)}}}")
        elif low == "end for":
            lines.append(r"\EndFor")
        elif re.match(r"^if\s.*\sthen$", low):
            body = re.sub(r"\s*then$", "", s, flags=re.I)
            body = re.sub(r"^if\s+", "", body, flags=re.I)
            lines.append(f"\\If{{{_escape_plain(body)}}}")
        elif low == "end if":
            lines.append(r"\EndIf")
        else:
            lines.append(r"\State " + _escape_plain(s) + comment)
    lines.append(r"\State \textbf{return} " + _escape_plain(b["ret"]))
    lines.append(r"\end{algorithmic}")
    lines.append(r"\end{algorithm}")
    return "\n".join(lines)


def latex_table(b):
    ncols = len(b["header"])
    if b.get("colw"):
        colspec = "".join(
            f">{{\\raggedright\\arraybackslash}}p{{{w}\\linewidth}}" for w in b["colw"]
        )
    else:
        colspec = "l" + "c" * (ncols - 1)
    lines = [r"\begin{table}[htbp]",
             r"\centering",
             r"\small",
             f"\\caption{{{resolve_citations(strip_manual_number(b['caption']))}}}",
             r"\resizebox{\linewidth}{!}{%" if not b.get("colw") else "",
             f"\\begin{{tabular}}{{{colspec}}}",
             r"\toprule"]
    lines.append(" & ".join(f"\\textbf{{{esc(h)}}}" for h in b["header"]) + r" \\")
    lines.append(r"\midrule")
    n_rows = len(b["rows"])
    for i, row in enumerate(b["rows"]):
        is_last = (i == n_rows - 1)
        bold = b.get("note") == "bold_last_row" and is_last
        cells = [esc(c) for c in row]
        if bold:
            cells = [f"\\textbf{{{c}}}" for c in cells]
        lines.append(" & ".join(cells) + r" \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    if not b.get("colw"):
        lines.append("}")
    if b.get("note") and b["note"] not in ("bold_last_row",):
        lines.append(r"\par\footnotesize " + esc(b["note"]))
    lines.append(r"\end{table}")
    return "\n".join(line for line in lines if line != "")


# ---------------------------------------------------------------------------
def author_block():
    lines = []
    for i, a in enumerate(C.AUTHORS, start=1):
        opts = ""
        lines.append(f"\\author[{i}]{{{esc(a['name'])}}}{opts}")
        if a.get("corresponding"):
            lines.append(f"\\cormark[1]")
            lines.append(r"\ead{" + C.CORRESPONDING_AUTHOR_EMAIL + "}")
        lines.append("")
    for i, aff in enumerate(C.AFFILIATIONS, start=1):
        lines.append(f"\\affiliation[{i}]{{organization={{{esc(aff)}}}}}")
    lines.append(r"\cortext[1]{Corresponding author}")
    return "\n".join(lines)


def build():
    body = latex_body()
    authors = author_block()
    keywords = " \\sep ".join(k.strip() for k in C.KEYWORDS.split(","))

    doc = TEMPLATE.format(
        title=esc(C.TITLE),
        authors=authors,
        abstract=resolve_citations(C.ABSTRACT),
        keywords=keywords,
        body=body,
    )
    out_path = os.path.join(LATEX_DIR, "manuscript.tex")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(doc)
    print("Wrote", out_path)


TEMPLATE = r"""\documentclass[a4paper,fleqn]{{cas-sc}}
\usepackage[authoryear,longnamesfirst]{{natbib}}
\usepackage{{algorithm}}
\usepackage{{algpseudocode}}
\usepackage{{booktabs}}

\begin{{document}}

\let\WriteBookmarks\relax
\def\floatpagepagefraction{{1}}
\def\textpagefraction{{.001}}

\shorttitle{{Meta-Prompted Instruction Refinement}}
\shortauthors{{Nguyen et al.}}

\title[mode=title]{{{title}}}

{authors}

\begin{{abstract}}
{abstract}
\end{{abstract}}

\begin{{keywords}}
{keywords}
\end{{keywords}}

\maketitle

{body}

\bibliographystyle{{cas-model2-names}}
\bibliography{{cas-refs}}

\end{{document}}
"""

if __name__ == "__main__":
    build()
